version: 2

jobs:
  build:
    working_directory: ~/brunch-map
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn
          command: yarn --pure-lockfile --cache-folder .yarn-cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn-cache
      - run:
          name: Build
          command: node_modules/.bin/gulp build --branch $CIRCLE_BRANCH
      - deploy:
          name: Deploy pre-supported branch
          command: |
            TOKEN=`eval echo '$FIREBASE_TOKEN_'$CIRCLE_BRANCH`
            node_modules/.bin/firebase use $CIRCLE_BRANCH --token $TOKEN
            node_modules/.bin/firebase deploy --token $TOKEN
