name: CI

on:
  push:
    branches: [staging]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          check-latest: true

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node

      - name: Install dependencies
        run: |
          npm ci

          cd ./app
          npm ci

          cd ../functions
          npm ci
          
      - name: Build ./app
        working-directory: ./app
        env:
          GOOGLE_MAPS_API_KEY: ${{secrets.GOOGLE_MAPS_API_KEY}}
        run: |
          npx webpack --env branch=${GITHUB_REF##*/}
      
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        run: |
          npx firebase use ${GITHUB_REF##*/}
          npx firebase deploy
